import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600", "700"]
});

export const metadata = {
  title: {
    default: 'Hero Kidz',
    template:'%s' | 'Hero Kidz'
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>

        <main className='py-2 md:w-11/12 mx-auto min-h-[calc(100vh-327px)] '>
          {children}
        </main>

        <footer>
          <Footer></Footer>
        </footer>

      </body>
    </html>
  );
}
