import React from 'react';
import ProductList from '../../components/home/ProductsList'

export const metadata = {
  title: 'All Products',
  description: "Generated by create next app",
};

const Products = () => {
    return (
        <div>
            <ProductList></ProductList>
        </div>
    );
};

export default Products;